import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, DotLoading, Empty, ErrorBlock, NavBar, Popup, SearchBar, Tabs, Tag, TextArea, Toast } from 'antd-mobile';
import { useNavigate } from 'react-router-dom';
import { useApi } from '../../hooks/useApi';
import { usePermission } from '../../hooks/usePermission';
import { CACHE_TIME } from '../../lib/queryClient';
import { fmtDate, fmtDateTime, fmtMoney, CUSTOMER_STATUS_COLOR } from '../../pages/_shared';
import { contractService } from '../../services/contractService';
import { customerService } from '../../services/customerService';
import { useAuthStore } from '../../stores/auth';
import type { Contract, Customer } from '../../types';
import { CustomerFollowUps } from './CustomerFollowUps';
import { displayUser } from './constants';
import type { AssignableUser, CustomerOperationLog, DetailRow } from './types';

const teal = '#158f82';
const card = { background: '#fff', borderRadius: 14, boxShadow: '0 2px 10px rgba(25,44,58,.05)' };
const popup = { borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: '18px 16px 30px' };
const quickButton = { flex: 1, border: '1px solid rgba(255,255,255,.55)', borderRadius: 8, padding: '7px 4px', color: '#fff', background: 'rgba(255,255,255,.14)', fontSize: 12 };
const contractStatusText = (status?: string) => ({ draft: '草稿', signing: '签约中', signed: '已签约', active: '服务中', replaced: '已换人', cancelled: '已作废', graduated: '已结单', refunded: '已退款' }[status || ''] || '待定');
const contractStatusColor = (status?: string) => status === 'refunded' ? 'danger' : ['cancelled', 'replaced'].includes(status || '') ? 'default' : 'primary';

function Grid({ title, rows }: { title: string; rows: DetailRow[] }) {
  return <section style={{ ...card, padding: 14, marginBottom: 10 }}><strong>{title}</strong><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 8, marginTop: 10 }}>{rows.map((row) => <div key={row.label} style={{ gridColumn: row.wide ? '1 / -1' : undefined, background: '#f7f9fa', borderRadius: 9, padding: '9px 10px', minWidth: 0 }}><div style={{ color: '#8a93a5', fontSize: 11 }}>{row.label}</div><div style={{ color: '#33404c', fontSize: 13, lineHeight: 1.45, wordBreak: 'break-word', marginTop: 3 }}>{row.value || '-'}</div></div>)}</div></section>;
}
function ContractCards({ contracts, onOpen }: { contracts: Contract[]; onOpen: (id: string) => void }) {
  return <>{contracts.map((item) => <div key={item._id} style={{ ...card, padding: 12, marginBottom: 10, border: item.contractStatus === 'active' ? `1px solid ${teal}` : undefined }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><div><b style={{ fontSize: 13 }}>{item.contractType || '服务合同'}</b><div style={{ color: '#687384', fontSize: 12, marginTop: 4 }}>服务阿姨：{item.workerName || '待定'}</div></div><Tag color={contractStatusColor(item.contractStatus)} style={{ alignSelf: 'flex-start', height: 'auto', lineHeight: '20px', margin: 0 }}>{contractStatusText(item.contractStatus)}</Tag></div><div style={{ display: 'flex', justifyContent: 'space-between', color: '#778293', fontSize: 12, marginTop: 10 }}><span>{[item.startDate && fmtDate(item.startDate), item.endDate && fmtDate(item.endDate)].filter(Boolean).join(' 至 ') || '服务周期待完善'}</span><b style={{ color: '#f08a24' }}>{fmtMoney(item.workerSalary || item.customerServiceFee)}</b></div><Button size="mini" fill="none" color="primary" onClick={() => onOpen(item._id)} style={{ marginTop: 8, padding: 0 }}>查看详情</Button></div>)}</>;
}
interface Props { id: string; onBack: () => void; onEdit: () => void; canEdit: boolean; openFollowUpOnMount?: boolean; }
export function CustomerDetailPrototype({ id, onBack, onEdit, canEdit, openFollowUpOnMount }: Props) {
  const [tab, setTab] = useState('overview'); const [followToken, setFollowToken] = useState(0); const [contracts, setContracts] = useState<Contract[]>([]); const [contractsLoading, setContractsLoading] = useState(false); const [logs, setLogs] = useState<CustomerOperationLog[] | null>(null); const [logsLoading, setLogsLoading] = useState(false);
  const [assignOpen, setAssignOpen] = useState(false); const [users, setUsers] = useState<AssignableUser[]>([]); const [query, setQuery] = useState(''); const [assignee, setAssignee] = useState(''); const [assignReason, setAssignReason] = useState(''); const [freezeOpen, setFreezeOpen] = useState(false); const [reasonMode, setReasonMode] = useState<'freeze' | 'release' | 'urgent' | null>(null); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [pushing, setPushing] = useState(false);
  const navigate = useNavigate(); const canCreateContract = usePermission('contract:create'); const role = useAuthStore((s) => s.user?.role); const admin = role === 'admin'; const canAssign = canEdit && ['admin', 'manager', 'operator'].includes(role || ''); const { data, loading, error, run } = useApi<Customer>(customerService.getCustomerById, { cacheKey: (value: string) => ['customer', value], staleTime: CACHE_TIME.detail.staleTime, gcTime: CACHE_TIME.detail.gcTime });
  const loadContracts = useCallback(async () => { setContractsLoading(true); try { setContracts(await contractService.getContractsByCustomerId(id)); } catch { setContracts([]); } finally { setContractsLoading(false); } }, [id]);
  useEffect(() => { run(id).catch(() => {}); loadContracts().catch(() => {}); }, [id, run, loadContracts]);
  useEffect(() => { if (openFollowUpOnMount) { setTab('followUps'); setFollowToken((n) => n + 1); } }, [openFollowUpOnMount]);
  useEffect(() => { if (tab !== 'operations' || !admin || logs !== null) return; setLogsLoading(true); customerService.getOperationLogs(id).then(setLogs).catch(() => setLogs([])).finally(() => setLogsLoading(false)); }, [tab, admin, id, logs]);
  const followCount = data && Array.isArray(data.followUps) ? data.followUps.length : Number(data?.followUpCount || 0);
  const risk = useMemo(() => { if (!data || !['O类', 'O'].includes(data.leadLevel || '')) return ''; const value = data.lastFollowUpTime || data.assignedAt || data.createdAt; if (!value) return 'O 类客户暂无跟进时间记录，建议立即联系。'; const days = Math.floor((Date.now() - new Date(value).getTime()) / 86400000); return days >= 1 ? `该客户为 O 类，已 ${days} 天未跟进，建议立即联系（O 类客户转化窗口为 24 小时）。` : ''; }, [data]);
  const refresh = async () => { await run(id); await loadContracts(); }; const action = async (work: () => Promise<unknown>, success: string) => { setBusy(true); try { await work(); await refresh(); Toast.show({ icon: 'success', content: success }); } catch (e: any) { Toast.show({ icon: 'fail', content: e?.response?.data?.message || e?.message || '操作失败，请重试' }); } finally { setBusy(false); } };
  const quickFollow = () => { if (!canEdit) { Toast.show({ icon: 'fail', content: '您没有新增跟进权限' }); return; } setTab('followUps'); setFollowToken((n) => n + 1); }; const createContract = () => { if (!data) return; if (!canCreateContract) { Toast.show({ icon: 'fail', content: '您没有创建合同权限' }); return; } navigate('/contracts', { state: { createForCustomer: data } }); };
  const openAssign = async () => { setAssignOpen(true); setAssignee(data?.assignedToUser?._id || data?.assignedTo || ''); if (users.length) return; try { setUsers(await customerService.getAssignableUsers()); } catch (e: any) { Toast.show({ icon: 'fail', content: e?.response?.data?.message || e?.message || '员工列表加载失败' }); } };
  const visibleUsers = users.filter((item) => `${item.name}${item.username}${item.role}`.toLowerCase().includes(query.toLowerCase())); const activeContracts = contracts.filter((item) => !['cancelled', 'refunded', 'replaced'].includes(item.contractStatus || '')); const historyContracts = contracts.filter((item) => !activeContracts.includes(item));
  return <div style={{ background: '#f5f7fa', minHeight: '100vh', paddingBottom: 74 }}><NavBar onBack={onBack} style={{ background: '#fff', position: 'sticky', top: 0, zIndex: 10, fontWeight: 700 }} right={<div style={{ display: 'flex', gap: 12, color: teal, fontSize: 13, position: 'absolute', right: 16, top: '50%', transform: 'translateY(-50%)', whiteSpace: 'nowrap' }}>{canEdit && <span onClick={onEdit}>编辑</span>}<span onClick={quickFollow}>立即跟进</span></div>}>客户详情</NavBar>{loading && !data && <div style={{ textAlign: 'center', padding: 28 }}><DotLoading color="primary" /></div>}{error && !data && <ErrorBlock status="default" title="加载失败" description="请返回后重试" style={{ padding: 24 }} />}
    {data && <><header style={{ color: '#fff', background: 'linear-gradient(135deg,#158f82,#27aea0)', padding: '16px 16px 14px' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><div style={{ minWidth: 0 }}><div style={{ display: 'flex', gap: 7, alignItems: 'center', flexWrap: 'wrap', fontSize: 20, fontWeight: 700 }}>{data.name}{data.isUrgent && ' 🚨'}{data.isStarred && <span style={{ color: '#ffe28a' }}>★</span>}<span style={{ borderRadius: 8, padding: '2px 6px', background: 'rgba(255,255,255,.2)', fontSize: 11 }}>{data.leadLevel || '未分级'}</span></div><div style={{ marginTop: 6, fontSize: 12 }}>#{data.customerId || data._id} · 📱 {data.phone || '-'} · {data.address || '地址待完善'}</div><div style={{ marginTop: 7, display: 'flex', gap: 5, flexWrap: 'wrap' }}>{[data.serviceCategory, data.followUpStatus].filter(Boolean).map((item) => <span key={String(item)} style={{ padding: '2px 6px', borderRadius: 7, background: 'rgba(255,255,255,.16)', fontSize: 11 }}>{String(item)}</span>)}</div></div><Tag color={CUSTOMER_STATUS_COLOR[data.contractStatus || ''] || 'default'} style={{ alignSelf: 'flex-start', height: 'auto', lineHeight: '20px', margin: 0 }}>{data.isFrozen ? '已冻结' : data.contractStatus || '待定'}</Tag></div><div style={{ display: 'flex', gap: 8, marginTop: 14 }}>{canAssign && <button onClick={openAssign} style={quickButton}>📤 分配</button>}<button onClick={createContract} style={quickButton}>📝 创建合同</button><a href={data.phone ? `tel:${data.phone}` : undefined} onClick={(event) => { if (!data.phone) { event.preventDefault(); Toast.show({ content: '该客户未填写联系电话' }); } }} style={{ ...quickButton, textAlign: 'center', textDecoration: 'none' }}>📞 拨打</a></div></header>
      <Tabs activeKey={tab} onChange={setTab} style={{ background: '#fff', '--title-font-size': '13px' }}><Tabs.Tab title="概览" key="overview" /><Tabs.Tab title="服务需求" key="requirements" /><Tabs.Tab title={`跟进${followCount ? ` ${followCount}` : ''}`} key="followUps" /><Tabs.Tab title={`合同${contracts.length ? ` ${contracts.length}` : ''}`} key="contracts" /><Tabs.Tab title={`操作${logs?.length ? ` ${logs.length}` : ''}`} key="operations" /><Tabs.Tab title="更多" key="management" /></Tabs>
      <main style={{ padding: 10 }}>{tab === 'overview' && <><Grid title="📋 基础信息" rows={[{ label: '客户 ID', value: data.customerId || data._id }, { label: '客户姓名', value: data.name }, { label: '手机号', value: data.phone }, { label: '微信号', value: data.wechatId || '-' }, { label: '身份证号', value: data.idCardNumber || '-' }, { label: '线索来源', value: data.leadSource || '-' }, { label: '线索等级', value: data.leadLevel || '-' }, { label: '跟进状态', value: data.followUpStatus || '-' }, { label: '当前负责人', value: displayUser(data.assignedToUser, data.assignedTo) }, { label: '签约状态', value: data.contractStatus || '-' }, { label: '分配时间', value: data.assignedAt ? fmtDateTime(data.assignedAt) : '-' }, { label: '最后更新', value: data.updatedAt ? fmtDateTime(data.updatedAt) : '-' }]} />{risk && <section style={{ ...card, padding: 14, borderLeft: '4px solid #ef5350', color: '#a33c3c', fontSize: 13, lineHeight: 1.55 }}>⚠️ {risk}</section>}</>}
        {tab === 'requirements' && <><Grid title="🎯 服务需求" rows={[{ label: '需求品类', value: data.serviceCategory || data.needOrderType || '-' }, { label: '薪资预算', value: fmtMoney(data.salaryBudget) }, { label: '休息方式', value: data.restSchedule || data.needRestTime || '-' }, { label: '期望上户日期', value: data.expectedStartDate ? fmtDate(data.expectedStartDate) : data.needOnboardingTime || '-' }, { label: '预产期', value: data.expectedDeliveryDate ? fmtDate(data.expectedDeliveryDate) : '-' }, { label: '服务天数', value: data.serviceDays ? `${data.serviceDays} 天/月` : '-' }, { label: '家庭面积', value: data.homeArea ? `${data.homeArea} ㎡` : data.needHouseArea || '-' }, { label: '家庭人口', value: data.familySize ? `${data.familySize} 人` : data.needFamilyMembers || '-' }, { label: '服务地址', value: data.address || data.needServiceAddress || '-', wide: true }]} /><Grid title="👤 阿姨要求" rows={[{ label: '年龄要求', value: data.ageRequirement || '-' }, { label: '性别要求', value: data.genderRequirement || '-' }, { label: '籍贯要求', value: data.originRequirement || '-' }, { label: '学历要求', value: data.educationRequirement || '-' }]} /><Grid title="📝 工作内容 & 备注" rows={[{ label: '工作时间', value: data.needWorkingHours || '-' }, { label: '服务周期', value: data.needServicePeriod || '-' }, { label: '成交金额', value: fmtMoney(data.dealAmount) }, { label: '工作内容', value: data.needWorkContent || '-', wide: true }, { label: '需求备注', value: data.needRemarks || data.remarks || '-', wide: true }]} /></>}
        {tab === 'followUps' && <div style={card}><CustomerFollowUps customerId={id} canEdit={canEdit} openFormToken={followToken} /></div>}
        {tab === 'contracts' && <>{contractsLoading ? <div style={{ textAlign: 'center', padding: 25 }}><DotLoading color="primary" /></div> : contracts.length === 0 ? <Empty description="暂无合同记录" /> : <><section style={{ ...card, padding: 12, color: '#51707d', fontSize: 13, marginBottom: 10 }}>💡 当前 {activeContracts.length} 单进行中，历史 {historyContracts.length} 单；每次换人均会保留新的合同记录。</section><ContractCards contracts={activeContracts} onOpen={(contractId) => navigate('/contracts', { state: { id: contractId } })} /><ContractCards contracts={historyContracts} onOpen={(contractId) => navigate('/contracts', { state: { id: contractId } })} /></>}</>}
        {tab === 'operations' && (admin ? <section style={{ ...card, padding: 14 }}><strong>📅 操作记录</strong>{logsLoading ? <div style={{ textAlign: 'center', padding: 24 }}><DotLoading color="primary" /></div> : !logs?.length ? <Empty description="暂无操作记录" /> : logs.map((log, index) => <div key={log._id || index} style={{ borderTop: '1px solid #eef1f3', padding: '10px 0', fontSize: 13, lineHeight: 1.55 }}><div style={{ color: '#8b96a6', fontSize: 11 }}>{log.operatedAt ? fmtDateTime(log.operatedAt) : '-'}</div><div><b>{log.operator?.name || log.operator?.username || '系统'}</b>　{log.operationName}{log.details?.description ? `：${log.details.description}` : ''}</div></div>)}</section> : <ErrorBlock status="default" title="操作日志仅管理员可查看" description="该数据受后端审计权限保护" />)}
        {tab === 'management' && <><Grid title="⚙️ 归属与系统信息" rows={[{ label: '当前负责人', value: displayUser(data.assignedToUser, data.assignedTo) }, { label: '分配备注', value: data.assignmentReason || '-' }, { label: '紧急状态', value: data.isUrgent ? `紧急：${data.urgentReason || '未填写原因'}` : '正常' }, { label: '冻结状态', value: data.isFrozen ? `已冻结：${data.frozenReason || '未填写原因'}` : '正常' }, { label: '公海状态', value: data.inPublicPool ? '在公海' : '非公海' }, { label: '流转次数', value: `${data.transferCount || 0} 次` }, { label: '创建人', value: displayUser(data.createdByUser, data.createdBy) }, { label: '创建时间', value: data.createdAt ? fmtDateTime(data.createdAt) : '-' }]} />{canEdit && <div style={{ display: 'grid', gap: 8 }}><Button fill="outline" color="primary" onClick={() => action(() => customerService.updateStar(id, !data.isStarred), data.isStarred ? '已取消星标' : '已加入星标')}>{data.isStarred ? '取消个人星标' : '加入个人星标'}</Button><Button fill="outline" color={data.isUrgent ? 'warning' : 'danger'} onClick={() => data.isUrgent ? action(() => customerService.updateUrgency(id, false), '已取消紧急标记') : setReasonMode('urgent')}>{data.isUrgent ? '取消紧急标记' : '标记紧急客户'}</Button><Button color="primary" loading={pushing} onClick={async () => { setPushing(true); try { await customerService.pushToAunties(id); Toast.show({ icon: 'success', content: '已发布至阿姨接单大厅' }); } catch (e: any) { Toast.show({ icon: 'fail', content: e?.response?.data?.message || e?.message || '发布失败' }); } finally { setPushing(false); } }}>发布至阿姨接单大厅</Button><Button fill="outline" color="danger" onClick={() => setReasonMode('release')}>释放线索至公海</Button></div>}</>}
      </main><footer style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 20, display: 'flex', gap: 8, padding: '9px 12px env(safe-area-inset-bottom)', background: '#fff', borderTop: '1px solid #e9edef' }}>{canAssign && <Button size="small" onClick={openAssign} style={{ flex: 1 }}>📤 分配</Button>}{admin && <Button size="small" color="warning" fill="outline" onClick={() => data.isFrozen ? action(() => customerService.unfreezeCustomer(id), '线索已解冻') : setFreezeOpen(true)} style={{ flex: 1 }}>{data.isFrozen ? '解冻' : '❄️ 冻结'}</Button>}<Button size="small" color="primary" onClick={quickFollow} style={{ flex: 1 }}>📞 立即跟进</Button></footer></>}
    <Popup visible={assignOpen} onMaskClick={() => !busy && setAssignOpen(false)} bodyStyle={popup}><h3>📤 分配客户给员工</h3><SearchBar value={query} onChange={setQuery} placeholder="搜索员工姓名或账号" /><div style={{ maxHeight: '36vh', overflowY: 'auto', margin: '10px 0' }}>{visibleUsers.map((item) => <div key={item._id} onClick={() => setAssignee(item._id)} style={{ padding: '10px 4px', borderBottom: '1px solid #f0f2f4', color: assignee === item._id ? teal : '#34414c' }}><b>{item.name || item.username}</b> <span style={{ color: '#8a93a5', fontSize: 12 }}>· {item.role}</span><span style={{ float: 'right' }}>{assignee === item._id ? '✓' : ''}</span></div>)}</div><TextArea value={assignReason} onChange={setAssignReason} placeholder="分配备注（可选）" rows={3} maxLength={200} showCount /><Actions busy={busy} cancel={() => setAssignOpen(false)} confirm={() => action(async () => { await customerService.assignCustomer(id, assignee, assignReason.trim() || undefined); setAssignOpen(false); }, '客户已重新分配')} disabled={!assignee} label="确认分配" /></Popup>
    <Popup visible={freezeOpen || !!reasonMode} onMaskClick={() => !busy && (setFreezeOpen(false), setReasonMode(null))} bodyStyle={popup}><h3>{freezeOpen ? '❄️ 冻结客户' : reasonMode === 'release' ? '释放线索至公海' : '标记紧急客户'}</h3><div style={{ color: '#a96818', fontSize: 13, marginBottom: 12 }}>{freezeOpen ? '冻结后客户无法参与线索流转或释放至公海；原因会写入正式审计记录。' : reasonMode === 'release' ? '释放后将取消当前负责人并进入公海；操作会保留审计记录。' : '紧急标记会在列表显示告警图标并记录原因。'}</div><TextArea value={reason} onChange={setReason} placeholder="请填写原因" rows={3} maxLength={200} showCount /><Actions busy={busy} cancel={() => { setFreezeOpen(false); setReasonMode(null); }} confirm={() => action(async () => { if (freezeOpen) await customerService.freezeCustomer(id, reason.trim()); else if (reasonMode === 'release') await customerService.releaseToPool(id, reason.trim()); else await customerService.updateUrgency(id, true, reason.trim()); setFreezeOpen(false); setReasonMode(null); setReason(''); }, freezeOpen ? '线索已冻结' : reasonMode === 'release' ? '客户已释放至公海' : '已标记紧急客户')} disabled={!reason.trim()} label={freezeOpen ? '确认冻结' : reasonMode === 'release' ? '确认释放' : '确认标记'} danger={reasonMode === 'release'} warning={freezeOpen} /></Popup>
  </div>;
}
function Actions({ busy, cancel, confirm, disabled, label, danger, warning }: { busy: boolean; cancel: () => void; confirm: () => void; disabled: boolean; label: string; danger?: boolean; warning?: boolean }) { return <div style={{ display: 'flex', gap: 10, marginTop: 18 }}><Button block disabled={busy} onClick={cancel}>取消</Button><Button block color={danger ? 'danger' : warning ? 'warning' : 'primary'} loading={busy} disabled={disabled || busy} onClick={confirm}>{label}</Button></div>; }